import { test, expect } from 'vitest';
import { runPipeline } from '../pipeline';
import { fixtureBuffer, readFixtureSheet } from './fixtures';

function asNum(v: unknown): number {
  if (v == null) return 0;
  return Number(v);
}
function asStr(v: unknown): string {
  if (v == null) return '';
  return String(v);
}
function asNullableNum(v: unknown): number | null {
  if (v == null || v === '') return null;
  return Number(v);
}

test('e2e: full pipeline matches Output_Updated.xlsx sheet by sheet', async () => {
  const orders = fixtureBuffer('inputs/Orders.xlsx');
  const income = fixtureBuffer('inputs/Income.xlsx');
  const result = await runPipeline(orders, income);

  // ---- Income Compiled ----
  // Output_E2E.xlsx is generated by the Python pipeline against the same inputs/Orders.xlsx + inputs/Income.xlsx
  const expectedCompiled = (await readFixtureSheet('Output_E2E.xlsx', 'Income Compiled')).map((r) => ({
    sku: asStr(r['SKU Reference No.']),
    orderId: asStr(r['Order ID']),
    productName: asStr(r['Product Name']),
    quantity: asNullableNum(r['Quantity']),
    totalOrderAmount: asNum(r['Total Order Amount']),
  }));
  expect(result.previews.compiled.length).toBe(expectedCompiled.length);
  for (let i = 0; i < expectedCompiled.length; i++) {
    const a = result.previews.compiled[i];
    const e = expectedCompiled[i];
    expect({ idx: i, sku: a.sku, orderId: a.orderId, productName: a.productName, quantity: a.quantity }).toEqual(
      { idx: i, sku: e.sku, orderId: e.orderId, productName: e.productName, quantity: e.quantity },
    );
    expect(a.totalOrderAmount).toBeCloseTo(e.totalOrderAmount, 2);
  }

  // ---- Pivot Table ----
  const expectedPivot = (await readFixtureSheet('Output_E2E.xlsx', 'Pivot Table')).map((r) => ({
    sku: asStr(r['SKU Reference No.']),
    totalQuantity: asNum(r['Total Quantity']),
    totalOrderAmount: asNum(r['Total Order Amount']),
  }));
  expect(result.previews.pivot.length).toBe(expectedPivot.length);
  for (let i = 0; i < expectedPivot.length; i++) {
    expect(result.previews.pivot[i].sku).toBe(expectedPivot[i].sku);
    expect(result.previews.pivot[i].totalQuantity).toBe(expectedPivot[i].totalQuantity);
    expect(result.previews.pivot[i].totalOrderAmount).toBeCloseTo(expectedPivot[i].totalOrderAmount, 2);
  }

  // ---- Income Summary ----
  const expectedSummaryRow = (await readFixtureSheet('Output_E2E.xlsx', 'Income Summary'))[0];
  expect(result.previews.summary.totalReleased).toBeCloseTo(asNum(expectedSummaryRow['Total Released Amount (S$)']), 2);
  expect(result.previews.summary.commissionFee).toBeCloseTo(asNum(expectedSummaryRow['Commission fee (Incl. GST)']), 2);
  expect(result.previews.summary.transactionFee).toBeCloseTo(asNum(expectedSummaryRow['Transaction Fee (Incl. Gst)']), 2);
  expect(result.previews.summary.totalShippingFee).toBeCloseTo(asNum(expectedSummaryRow['Total Shipping Fee']), 2);
});
