import { test, expect } from 'vitest';
import { runPipeline } from '../pipeline';
import { fixtureBuffer } from './fixtures';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

// Use Feb 2026 income with Feb + Jan orders (per task-3 fixture mapping).
// Output_E2E.xlsx was generated by a stale Python pipeline against different inputs
// and is no longer authoritative. We assert against the authoritative Summary-tab
// values from the Feb 2026 income fixture instead.
test('e2e: full pipeline produces correct structural output for Feb 2026', async () => {
  const orders = readFileSync(join(__dirname, 'fixtures/orders/2026-02.xlsx'));
  const ordersPrev = readFileSync(join(__dirname, 'fixtures/orders/2026-01.xlsx'));
  const income = readFileSync(join(__dirname, 'fixtures/income/2026-02.xlsx'));
  const result = await runPipeline(orders, ordersPrev, income);

  // ---- Income Compiled ----
  // Must contain product rows plus synthetic rows (RF/LC/TF/CF/SF/VR/SC/AJ)
  expect(result.previews.compiled.length).toBeGreaterThan(0);
  const compiledSkus = new Set(result.previews.compiled.map((r) => r.sku));
  // Synthetic rows present in any real month
  expect(compiledSkus.has('TF')).toBe(true);  // transaction fee rows always present
  expect(compiledSkus.has('CF')).toBe(true);  // commission fee rows always present

  // ---- Product Breakdown ----
  // Replaces the old Pivot Table; must be non-empty and contain real SKUs
  expect(result.previews.breakdown.length).toBeGreaterThan(0);
  // Each breakdown row must have a non-empty sku and a non-negative totalQuantity
  for (const row of result.previews.breakdown) {
    expect(typeof row.sku).toBe('string');
    expect(row.sku.length).toBeGreaterThan(0);
    expect(row.totalQuantity).toBeGreaterThanOrEqual(0);
  }

  // ---- Income Summary ----
  // Assert against authoritative Summary-tab values from the Feb 2026 income fixture.
  // totalReleased = sum of Income-tab rows (income rows), not Summary tab.
  expect(result.previews.summary.totalReleased).toBeCloseTo(36005.18, 2);
  // The commissionFee, transactionFee, serviceFee come directly from the Summary tab.
  expect(result.previews.summary.commissionFee).toBeCloseTo(-3296.34, 2);
  expect(result.previews.summary.transactionFee).toBeCloseTo(-1416.87, 2);
  expect(result.previews.summary.serviceFee).toBeCloseTo(-1428.44, 2);
  expect(result.previews.summary.totalExpenses).toBeCloseTo(-7196.85, 2);
  // actualReleased = Summary-tab totalReleased + adjustments = 36005.18 + 41.20
  expect(result.previews.summary.actualReleased).toBeCloseTo(36046.38, 2);
  expect(result.previews.summary.adjustments).toBeCloseTo(41.20, 2);

  // ---- Reconciliation ----
  expect(result.reconciliation).toHaveProperty('actualReleased');
  expect(result.reconciliation).toHaveProperty('attributedReleased');
  expect(result.reconciliation).toHaveProperty('releasedGap');
  expect(result.reconciliation).toHaveProperty('flagged');
  expect(result.reconciliation.actualReleased).toBeCloseTo(36046.38, 2);

  // ---- Unmatched ----
  expect(result.unmatched).toHaveProperty('count');
  expect(result.unmatched.rows.length).toBe(result.unmatched.count);

  // ---- Workbook ----
  expect(Buffer.isBuffer(result.workbook)).toBe(true);
  expect(result.workbook.length).toBeGreaterThan(1000);
});
